export * from "./auth.docs";
export * from "./user.docs";
export * from "./admin.docs";
export * from "./sales.docs";
export * from "./invoices.docs";
export * from "./products.docs";
export * from "./analytics.docs";
export * from "./receipts.docs";
export * from "./productCategory.docs";
